# Generated by Django 5.1 on 2024-09-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_released',
            field=models.BooleanField(default=False, help_text='Indicates if the movie is released and tickets can be purchased'),
        ),
    ]
